# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.18

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/valen/Course_work

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/valen/Course_work

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/valen/Course_work/CMakeFiles /home/valen/Course_work//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/valen/Course_work/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Course_work

# Build rule for target.
Course_work: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Course_work
.PHONY : Course_work

# fast build rule for target.
Course_work/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Course_work.dir/build.make CMakeFiles/Course_work.dir/build
.PHONY : Course_work/fast

algorithms/common_array.o: algorithms/common_array.c.o

.PHONY : algorithms/common_array.o

# target to build an object file
algorithms/common_array.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Course_work.dir/build.make CMakeFiles/Course_work.dir/algorithms/common_array.c.o
.PHONY : algorithms/common_array.c.o

algorithms/common_array.i: algorithms/common_array.c.i

.PHONY : algorithms/common_array.i

# target to preprocess a source file
algorithms/common_array.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Course_work.dir/build.make CMakeFiles/Course_work.dir/algorithms/common_array.c.i
.PHONY : algorithms/common_array.c.i

algorithms/common_array.s: algorithms/common_array.c.s

.PHONY : algorithms/common_array.s

# target to generate assembly for a file
algorithms/common_array.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Course_work.dir/build.make CMakeFiles/Course_work.dir/algorithms/common_array.c.s
.PHONY : algorithms/common_array.c.s

algorithms/hybrid_select_1_exchange.o: algorithms/hybrid_select_1_exchange.c.o

.PHONY : algorithms/hybrid_select_1_exchange.o

# target to build an object file
algorithms/hybrid_select_1_exchange.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Course_work.dir/build.make CMakeFiles/Course_work.dir/algorithms/hybrid_select_1_exchange.c.o
.PHONY : algorithms/hybrid_select_1_exchange.c.o

algorithms/hybrid_select_1_exchange.i: algorithms/hybrid_select_1_exchange.c.i

.PHONY : algorithms/hybrid_select_1_exchange.i

# target to preprocess a source file
algorithms/hybrid_select_1_exchange.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Course_work.dir/build.make CMakeFiles/Course_work.dir/algorithms/hybrid_select_1_exchange.c.i
.PHONY : algorithms/hybrid_select_1_exchange.c.i

algorithms/hybrid_select_1_exchange.s: algorithms/hybrid_select_1_exchange.c.s

.PHONY : algorithms/hybrid_select_1_exchange.s

# target to generate assembly for a file
algorithms/hybrid_select_1_exchange.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Course_work.dir/build.make CMakeFiles/Course_work.dir/algorithms/hybrid_select_1_exchange.c.s
.PHONY : algorithms/hybrid_select_1_exchange.c.s

algorithms/select_6_sorting.o: algorithms/select_6_sorting.c.o

.PHONY : algorithms/select_6_sorting.o

# target to build an object file
algorithms/select_6_sorting.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Course_work.dir/build.make CMakeFiles/Course_work.dir/algorithms/select_6_sorting.c.o
.PHONY : algorithms/select_6_sorting.c.o

algorithms/select_6_sorting.i: algorithms/select_6_sorting.c.i

.PHONY : algorithms/select_6_sorting.i

# target to preprocess a source file
algorithms/select_6_sorting.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Course_work.dir/build.make CMakeFiles/Course_work.dir/algorithms/select_6_sorting.c.i
.PHONY : algorithms/select_6_sorting.c.i

algorithms/select_6_sorting.s: algorithms/select_6_sorting.c.s

.PHONY : algorithms/select_6_sorting.s

# target to generate assembly for a file
algorithms/select_6_sorting.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Course_work.dir/build.make CMakeFiles/Course_work.dir/algorithms/select_6_sorting.c.s
.PHONY : algorithms/select_6_sorting.c.s

algorithms/shell_1_sorting.o: algorithms/shell_1_sorting.c.o

.PHONY : algorithms/shell_1_sorting.o

# target to build an object file
algorithms/shell_1_sorting.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Course_work.dir/build.make CMakeFiles/Course_work.dir/algorithms/shell_1_sorting.c.o
.PHONY : algorithms/shell_1_sorting.c.o

algorithms/shell_1_sorting.i: algorithms/shell_1_sorting.c.i

.PHONY : algorithms/shell_1_sorting.i

# target to preprocess a source file
algorithms/shell_1_sorting.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Course_work.dir/build.make CMakeFiles/Course_work.dir/algorithms/shell_1_sorting.c.i
.PHONY : algorithms/shell_1_sorting.c.i

algorithms/shell_1_sorting.s: algorithms/shell_1_sorting.c.s

.PHONY : algorithms/shell_1_sorting.s

# target to generate assembly for a file
algorithms/shell_1_sorting.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Course_work.dir/build.make CMakeFiles/Course_work.dir/algorithms/shell_1_sorting.c.s
.PHONY : algorithms/shell_1_sorting.c.s

main.o: main.c.o

.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Course_work.dir/build.make CMakeFiles/Course_work.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i

.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Course_work.dir/build.make CMakeFiles/Course_work.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s

.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Course_work.dir/build.make CMakeFiles/Course_work.dir/main.c.s
.PHONY : main.c.s

time_measurement/measure_options.o: time_measurement/measure_options.c.o

.PHONY : time_measurement/measure_options.o

# target to build an object file
time_measurement/measure_options.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Course_work.dir/build.make CMakeFiles/Course_work.dir/time_measurement/measure_options.c.o
.PHONY : time_measurement/measure_options.c.o

time_measurement/measure_options.i: time_measurement/measure_options.c.i

.PHONY : time_measurement/measure_options.i

# target to preprocess a source file
time_measurement/measure_options.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Course_work.dir/build.make CMakeFiles/Course_work.dir/time_measurement/measure_options.c.i
.PHONY : time_measurement/measure_options.c.i

time_measurement/measure_options.s: time_measurement/measure_options.c.s

.PHONY : time_measurement/measure_options.s

# target to generate assembly for a file
time_measurement/measure_options.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Course_work.dir/build.make CMakeFiles/Course_work.dir/time_measurement/measure_options.c.s
.PHONY : time_measurement/measure_options.c.s

time_measurement/time_measurement_processing.o: time_measurement/time_measurement_processing.c.o

.PHONY : time_measurement/time_measurement_processing.o

# target to build an object file
time_measurement/time_measurement_processing.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Course_work.dir/build.make CMakeFiles/Course_work.dir/time_measurement/time_measurement_processing.c.o
.PHONY : time_measurement/time_measurement_processing.c.o

time_measurement/time_measurement_processing.i: time_measurement/time_measurement_processing.c.i

.PHONY : time_measurement/time_measurement_processing.i

# target to preprocess a source file
time_measurement/time_measurement_processing.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Course_work.dir/build.make CMakeFiles/Course_work.dir/time_measurement/time_measurement_processing.c.i
.PHONY : time_measurement/time_measurement_processing.c.i

time_measurement/time_measurement_processing.s: time_measurement/time_measurement_processing.c.s

.PHONY : time_measurement/time_measurement_processing.s

# target to generate assembly for a file
time_measurement/time_measurement_processing.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Course_work.dir/build.make CMakeFiles/Course_work.dir/time_measurement/time_measurement_processing.c.s
.PHONY : time_measurement/time_measurement_processing.c.s

user_interface/menu.o: user_interface/menu.c.o

.PHONY : user_interface/menu.o

# target to build an object file
user_interface/menu.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Course_work.dir/build.make CMakeFiles/Course_work.dir/user_interface/menu.c.o
.PHONY : user_interface/menu.c.o

user_interface/menu.i: user_interface/menu.c.i

.PHONY : user_interface/menu.i

# target to preprocess a source file
user_interface/menu.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Course_work.dir/build.make CMakeFiles/Course_work.dir/user_interface/menu.c.i
.PHONY : user_interface/menu.c.i

user_interface/menu.s: user_interface/menu.c.s

.PHONY : user_interface/menu.s

# target to generate assembly for a file
user_interface/menu.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Course_work.dir/build.make CMakeFiles/Course_work.dir/user_interface/menu.c.s
.PHONY : user_interface/menu.c.s

user_interface/spreadsheet.o: user_interface/spreadsheet.c.o

.PHONY : user_interface/spreadsheet.o

# target to build an object file
user_interface/spreadsheet.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Course_work.dir/build.make CMakeFiles/Course_work.dir/user_interface/spreadsheet.c.o
.PHONY : user_interface/spreadsheet.c.o

user_interface/spreadsheet.i: user_interface/spreadsheet.c.i

.PHONY : user_interface/spreadsheet.i

# target to preprocess a source file
user_interface/spreadsheet.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Course_work.dir/build.make CMakeFiles/Course_work.dir/user_interface/spreadsheet.c.i
.PHONY : user_interface/spreadsheet.c.i

user_interface/spreadsheet.s: user_interface/spreadsheet.c.s

.PHONY : user_interface/spreadsheet.s

# target to generate assembly for a file
user_interface/spreadsheet.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Course_work.dir/build.make CMakeFiles/Course_work.dir/user_interface/spreadsheet.c.s
.PHONY : user_interface/spreadsheet.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Course_work"
	@echo "... algorithms/common_array.o"
	@echo "... algorithms/common_array.i"
	@echo "... algorithms/common_array.s"
	@echo "... algorithms/hybrid_select_1_exchange.o"
	@echo "... algorithms/hybrid_select_1_exchange.i"
	@echo "... algorithms/hybrid_select_1_exchange.s"
	@echo "... algorithms/select_6_sorting.o"
	@echo "... algorithms/select_6_sorting.i"
	@echo "... algorithms/select_6_sorting.s"
	@echo "... algorithms/shell_1_sorting.o"
	@echo "... algorithms/shell_1_sorting.i"
	@echo "... algorithms/shell_1_sorting.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... time_measurement/measure_options.o"
	@echo "... time_measurement/measure_options.i"
	@echo "... time_measurement/measure_options.s"
	@echo "... time_measurement/time_measurement_processing.o"
	@echo "... time_measurement/time_measurement_processing.i"
	@echo "... time_measurement/time_measurement_processing.s"
	@echo "... user_interface/menu.o"
	@echo "... user_interface/menu.i"
	@echo "... user_interface/menu.s"
	@echo "... user_interface/spreadsheet.o"
	@echo "... user_interface/spreadsheet.i"
	@echo "... user_interface/spreadsheet.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

